# Simple Example to test a pre-trained VGGVox for speaker identification using a small VoxCeleb1 dataset

* ## This Notebook has been adapted from:

https://github.com/Derpimort/VGGVox-PyTorch

https://rzimmermann.com/coding/vggvox-pytorch


* ## Clonar el github: VGGVox PyTorch

In [2]:
! git clone https://github.com/Derpimort/VGGVox-PyTorch.git

Cloning into 'VGGVox-PyTorch'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 101 (delta 1), reused 5 (delta 1), pack-reused 93
Receiving objects: 100% (101/101), 64.81 MiB | 38.72 MiB/s, done.
Resolving deltas: 100% (50/50), done.


In [3]:
! df -a

Filesystem     1K-blocks     Used Available Use% Mounted on
overlay         71724152 33889048  37818720  48% /
proc                   0        0         0    - /proc
tmpfs              65536        0     65536   0% /dev
devpts                 0        0         0    - /dev/pts
sysfs                  0        0         0    - /sys
tmpfs            6666796        0   6666796   0% /sys/fs/cgroup
cgroup                 0        0         0    - /sys/fs/cgroup/systemd
cgroup                 0        0         0    - /sys/fs/cgroup/cpuset
cgroup                 0        0         0    - /sys/fs/cgroup/devices
cgroup                 0        0         0    - /sys/fs/cgroup/net_cls,net_prio
cgroup                 0        0         0    - /sys/fs/cgroup/hugetlb
cgroup                 0        0         0    - /sys/fs/cgroup/cpu,cpuacct
cgroup                 0        0         0    - /sys/fs/cgroup/perf_event
cgroup                 0        0         0    - /sys/fs/cgroup/memory
cgroup        

In [1]:
ls ./VGGVox-PyTorch/

data/    models/        README.md         results.txt      test.wav  vggm.py
LICENSE  model_test.py  requirements.txt  signal_utils.py  train.py


## * Change the current directory to /content/VGGVox-PyTorch

In [22]:
cd /content/VGGVox-PyTorch


/content/VGGVox-PyTorch


# Install packages
# <font color=red>WARNING!!! once installed, you have to reset the virtual machine (see the warning message)

In [6]:
! pip install -r requirements.txt

# LET's see what data do we need

In [3]:
ls -al ./data/

total 5228
drwxr-xr-x 2 root root    4096 Nov 24 19:02 ./
drwxr-xr-x 5 root root    4096 Nov 24 19:02 ../
-rw-r--r-- 1 root root 4912512 Nov 24 19:02 iden_split.txt
-rw-r--r-- 1 root root  387503 Nov 24 19:02 val.pkl
-rw-r--r-- 1 root root   40782 Nov 24 19:02 vox1_meta.csv


In [23]:
cd ./data

/content/VGGVox-PyTorch/data


* ## we create a directory /content/VGGVox-PyTorch/data/VoxCeleb1
> ## to copy some VoxCeleb1 data to test

In [24]:
! mkdir ./VoxCeleb1

mkdir: cannot create directory ‘./VoxCeleb1’: File exists


In [25]:
cd ./VoxCeleb1/

/content/VGGVox-PyTorch/data/VoxCeleb1


* ## we create a directory for wav files /content/VGGVox-PyTorch/data/VoxCeleb1/wav

In [26]:
! mkdir ./wav

In [27]:
pwd

'/content/VGGVox-PyTorch/data/VoxCeleb1'

# DownLoad VoxCeleb1

* # This is to download all, BUT it doen't fit!!! 
#### !wget --user=voxceleb1912 --password=MYPasswd http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partab
* # so I try with a small subset in my drive

> The data is in a zip file: **id10270.zip**


In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [28]:
ls /content/drive/'My Drive'/VGGVOX_PyTorch

id10270.zip  VGGVox_1.ipynb


In [29]:
ls /content/VGGVox-PyTorch/data/

iden_split.txt  val.pkl  vox1_meta.csv  VoxCeleb1/  wav/


In [30]:
cp /content/drive/'My Drive'/VGGVOX_PyTorch/id10270.zip /content/VGGVox-PyTorch/data/VoxCeleb1/wav/.

In [31]:
ls /content/VGGVox-PyTorch/data/VoxCeleb1/wav

id10270.zip


In [32]:
cd /content/VGGVox-PyTorch/data/VoxCeleb1/wav

/content/VGGVox-PyTorch/data/VoxCeleb1/wav


In [33]:
!unzip id10270.zip

Archive:  id10270.zip
   creating: id10270/
   creating: id10270/5r0dWxy17C8/
  inflating: id10270/5r0dWxy17C8/00001.wav  
  inflating: id10270/5r0dWxy17C8/00002.wav  
  inflating: id10270/5r0dWxy17C8/00003.wav  
  inflating: id10270/5r0dWxy17C8/00004.wav  
  inflating: id10270/5r0dWxy17C8/00005.wav  
  inflating: id10270/5r0dWxy17C8/00006.wav  
  inflating: id10270/5r0dWxy17C8/00007.wav  
  inflating: id10270/5r0dWxy17C8/00008.wav  
  inflating: id10270/5r0dWxy17C8/00009.wav  
  inflating: id10270/5r0dWxy17C8/00010.wav  
  inflating: id10270/5r0dWxy17C8/00011.wav  
  inflating: id10270/5r0dWxy17C8/00012.wav  
  inflating: id10270/5r0dWxy17C8/00013.wav  
  inflating: id10270/5r0dWxy17C8/00014.wav  
  inflating: id10270/5r0dWxy17C8/00015.wav  
  inflating: id10270/5r0dWxy17C8/00016.wav  
  inflating: id10270/5r0dWxy17C8/00017.wav  
  inflating: id10270/5r0dWxy17C8/00018.wav  
  inflating: id10270/5r0dWxy17C8/00019.wav  
  inflating: id10270/5r0dWxy17C8/00020.wav  
  inflating: id10270/5

In [34]:
! rm *.zip

In [35]:
cd ..

/content/VGGVox-PyTorch/data/VoxCeleb1


In [36]:
ls ./wav

id10270/


---
---


# Now we are going to extract the embeddings from these wav files

* ## **IT IS IMPORTANT TO MOVE to the VGGVox-PyTorch directory**

In [37]:
cd /content/VGGVox-PyTorch

/content/VGGVox-PyTorch


In [38]:
pwd

'/content/VGGVox-PyTorch'

In [39]:
import os
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Subset, Dataset, DataLoader
from tqdm.auto import tqdm
from vggm import VGGM
import argparse
from train import AudioDataset, accuracy, ppdf, LOCAL_DATA_DIR, MODEL_DIR


In [40]:
LOCAL_DATA_DIR = '/content/VGGVox-PyTorch/data/'

print(LOCAL_DATA_DIR)

/content/VGGVox-PyTorch/data/


* ## This csv contains the IDs of VoxCeleb : vox1_meta.csv



In [41]:

df_meta=pd.read_csv(LOCAL_DATA_DIR+"vox1_meta.csv",sep="\t")

In [42]:
df_meta.head(10)

VoxCeleb1 ID      VGGFace1 ID Gender Nationality  Set
0      id10001     A.J._Buckley      m     Ireland  dev
1      id10002      A.R._Rahman      m       India  dev
2      id10003       Aamir_Khan      m       India  dev
3      id10004      Aaron_Tveit      m         USA  dev
4      id10005        Aaron_Yoo      m         USA  dev
5      id10006    Abbie_Cornish      f   Australia  dev
6      id10007  Abigail_Breslin      f         USA  dev
7      id10008  Abigail_Spencer      f         USA  dev
8      id10009       Adam_Beach      m      Canada  dev
9      id10010       Adam_Brody      m         USA  dev

# This text file contains wav files root, labels, train/devel/test : iden_split.txt

In [43]:
df_F=pd.read_csv(LOCAL_DATA_DIR+"iden_split.txt", sep=" ", names=["Set","Path"] )
df_F=ppdf(df_F)

In [44]:
df_F.head(10)

Set                               Path    Label
0    3  wav/id10003/na8-QEFmj44/00003.wav  10003.0
1    1  wav/id10003/tCq2LcKO6xY/00002.wav  10003.0
2    1  wav/id10003/K5zRxtXc27s/00001.wav  10003.0
3    1  wav/id10003/bDxy7bnj_bc/00004.wav  10003.0
4    1  wav/id10003/E_6MjfYr0sQ/00011.wav  10003.0
5    1  wav/id10003/5ablueV_1tw/00010.wav  10003.0
6    1  wav/id10003/BQxxhq4539A/00016.wav  10003.0
7    1  wav/id10003/yzIXg93UOIM/00029.wav  10003.0
8    1  wav/id10003/BQxxhq4539A/00007.wav  10003.0
9    1  wav/id10003/bDxy7bnj_bc/00006.wav  10003.0

# We select only the available data that we have: corresponds to this ID 10270 

In [46]:
df_10270 = df_F[(df_F['Set']==3 ) &  (df_F['Label']==10270.0 )]

df_10270.head(5)

Set                               Path    Label
32146    3  wav/id10270/x6uYqmx31kE/00006.wav  10270.0
32155    3  wav/id10270/x6uYqmx31kE/00009.wav  10270.0
32158    3  wav/id10270/x6uYqmx31kE/00011.wav  10270.0
32167    3  wav/id10270/x6uYqmx31kE/00012.wav  10270.0
32169    3  wav/id10270/x6uYqmx31kE/00019.wav  10270.0

* # NOTE the DATA_DIR and that wav is in the txt file

In [47]:
DATA_DIR = '/content/VGGVox-PyTorch/data/VoxCeleb1/'

In [48]:
ls /content/VGGVox-PyTorch/data/VoxCeleb1/

wav/


In [49]:
#Datasets={
#        "test":AudioDataset(df_F[df_F['Set']==3], DATA_DIR, is_train=False)}

Datasets={
        "test":AudioDataset(df_10270, DATA_DIR, is_train=False)}

In [50]:
Dataloaders={i:DataLoader(Datasets[i], batch_size=1, shuffle=False, num_workers=2) for i in Datasets}

In [51]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [52]:
MODEL_DIR

'models/'

In [53]:
cd /content/VGGVox-PyTorch/

/content/VGGVox-PyTorch


In [54]:
ls ./models

VGGM300_BEST_140_81.99.pth


In [55]:
model=VGGM(1251)
#model.load_state_dict(torch.load(DATA_DIR+"/VGGMVAL_BEST_149_80.84.pth", map_location=device))
model.load_state_dict(torch.load(MODEL_DIR+"VGGM300_BEST_140_81.99.pth", map_location=device))
model.to(device)
model.eval()

VGGM(
  (features): Sequential(
    (conv1): Conv2d(1, 96, kernel_size=(7, 7), stride=(2, 2), padding=(1, 1))
    (bn1): BatchNorm2d(96, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
    (relu1): ReLU()
    (mpool1): MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
    (conv2): Conv2d(96, 256, kernel_size=(5, 5), stride=(2, 2), padding=(1, 1))
    (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
    (relu2): ReLU()
    (mpool2): MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
    (conv3): Conv2d(256, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn3): BatchNorm2d(384, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
    (relu3): ReLU()
    (conv4): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn4): BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True)
    (relu4): ReLU()
   

In [56]:
def test(model, Dataloaders):
    corr1=0
    corr5=0
    counter=0
    top1=0
    top5=0
    for audio, labels in Dataloaders:
        audio = audio.to(device)
        labels = labels.to(device)
        outputs = model(audio)
        
        print( 'labels: ', labels, 'output: ', outputs)
        corr1, corr5=accuracy(outputs, labels, topk=(1,5))
        top1+=corr1
        top5+=corr5
    # max returns (value ,index)
        counter+=1
    print("\nTop-1 accuracy: %.5f\nTop-5 accuracy: %.5f"%(top1/counter, top5/counter))
    return top1/counter, top5/counter

In [57]:
print("\nTest Score:\n")
acc1=test(model, Dataloaders['test'])


Test Score:

labels:  tensor([269], device='cuda:0') output:  tensor([[ 0.6497,  1.1976,  1.7840,  ...,  3.9692, -0.2092, -3.8309]],
       device='cuda:0', grad_fn=<AddmmBackward>)
labels:  tensor([269], device='cuda:0') output:  tensor([[ 1.3369,  4.8396,  3.4511,  ...,  1.3770, -2.3983, -7.7501]],
       device='cuda:0', grad_fn=<AddmmBackward>)
labels:  tensor([269], device='cuda:0') output:  tensor([[ 0.9749,  5.8992,  2.7150,  ...,  1.7680, -3.1625, -4.0761]],
       device='cuda:0', grad_fn=<AddmmBackward>)
labels:  tensor([269], device='cuda:0') output:  tensor([[ 1.4344,  6.4688,  2.5059,  ...,  0.9005, -6.9621, -3.7017]],
       device='cuda:0', grad_fn=<AddmmBackward>)
labels:  tensor([269], device='cuda:0') output:  tensor([[ 0.0504,  5.2183,  7.8084,  ...,  3.0531, -4.1692, -4.8371]],
       device='cuda:0', grad_fn=<AddmmBackward>)
labels:  tensor([269], device='cuda:0') output:  tensor([[-2.2749,  9.6972,  4.2339,  ...,  2.1629, -5.3547, -3.9640]],
       device='cuda:0

# EXTRACTION OF EMBEDDINGS !!!

* # NOTE that the network has two parts features and classification

In [61]:
list(VGGM().features)

[Conv2d(1, 96, kernel_size=(7, 7), stride=(2, 2), padding=(1, 1)),
 BatchNorm2d(96, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True),
 ReLU(),
 MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=0, dilation=1, ceil_mode=False),
 Conv2d(96, 256, kernel_size=(5, 5), stride=(2, 2), padding=(1, 1)),
 BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True),
 ReLU(),
 MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=0, dilation=1, ceil_mode=False),
 Conv2d(256, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)),
 BatchNorm2d(384, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True),
 ReLU(),
 Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)),
 BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True),
 ReLU(),
 Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)),
 BatchNorm2d(256, eps=1e-05, momentum=0.5, affine=True, track_running_stats=True),
 ReLU(),
 MaxPool2d(kernel_siz

In [62]:
print(model.classifier)

Sequential(
  (fc7): Linear(in_features=4096, out_features=1024, bias=True)
  (relu7): ReLU()
  (fc8): Linear(in_features=1024, out_features=1251, bias=True)
)


## This is to extract an activation from one layer ...

In [64]:
activation = {}
def get_activation(name):
    def hook(model, input, output):
        activation[name] = output.detach()
    return hook

# Now we test it!

In [65]:
def test_embeddings(model, Dataloaders):

    for audio, labels in Dataloaders:
        audio = audio.to(device)
        labels = labels.to(device)
        model.classifier.fc7.register_forward_hook(get_activation('fc7'))
        outputs = model(audio)
        
        print(activation['fc7'])

In [66]:
test_embeddings(model, Dataloaders['test'])

tensor([[-2.8488e-11, -5.8916e-11, -4.9629e-10,  ...,  1.1575e+01,
         -3.7627e-11, -3.5425e-11]], device='cuda:0')
tensor([[-3.2383e-11, -6.1420e-11, -4.9148e-10,  ...,  1.0527e+01,
         -3.8229e-11, -3.2723e-11]], device='cuda:0')
tensor([[-3.4596e-11, -6.3217e-11, -5.4567e-10,  ...,  1.0744e+01,
         -4.2171e-11, -3.7380e-11]], device='cuda:0')
tensor([[-3.3896e-11, -6.8122e-11, -5.3622e-10,  ...,  1.3883e+01,
         -4.2113e-11, -3.5100e-11]], device='cuda:0')
tensor([[-3.0619e-11, -6.5882e-11, -5.4377e-10,  ...,  9.5368e+00,
         -4.3931e-11, -3.5793e-11]], device='cuda:0')
tensor([[-3.1345e-11, -6.1455e-11, -5.3150e-10,  ...,  1.1067e+01,
         -3.9604e-11, -3.2866e-11]], device='cuda:0')
tensor([[-3.1289e-11, -5.7579e-11, -4.9879e-10,  ...,  5.9615e+00,
         -3.7919e-11, -2.9192e-11]], device='cuda:0')
tensor([[-3.1151e-11, -6.2389e-11, -4.9415e-10,  ...,  1.3377e+01,
         -3.7528e-11, -3.1634e-11]], device='cuda:0')
tensor([[-3.3273e-11, -6.9724e-1

# Activation is a python dictionary that contains the activation of the specified layer or layers...

In [67]:
activation.keys()

dict_keys(['fc7'])

In [68]:
activation['fc7'].shape

torch.Size([1, 1024])

* # NEXT I'm going to try a simple Notebook extracting embeddings from a wav file

VGGVox_Embeddings_Simple.ipynb